version: '3.1'
services:
  proxy:
    image: nginx:1.21.3-alpine
    container_name: nginx-proxy
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./log/:/var/log/nginx/
    ports:
      - 80:80

